#include "analysis/Analysis.hpp"
#include "ga/Fitness.hpp"
#include "ga/GAEngine.hpp"
#include "preprocessing/AdsbDataPreprocessor.hpp"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

void printUsage(const char* progName) {
  std::cout << "Usage: " << progName << " <adsb_csv_file> [options]\n\n";
  std::cout << "Options:\n";
  std::cout << "  --generations N    Number of GA generations (default: 100)\n";
  std::cout << "  --population N     Population size (default: 100)\n";
  std::cout << "  --train-split R    Training split ratio 0.0-1.0 (default: 0.8)\n";
  std::cout
      << "  --output FILE      Output file for results (default: results/optimized_params.txt)\n";
  std::cout << "\nExample:\n";
  std::cout << "  " << progName << " data/flight_data.csv --generations 100 --population 200\n";
}

void saveOptimizedParameters(const std::string& filename, const ga::Chromosome& best,
                             const analysis::ValidationMetrics& trainMetrics,
                             const analysis::ValidationMetrics& valMetrics) {
  std::ofstream out(filename);
  if (!out.is_open()) {
    std::cerr << "Warning: Could not save parameters to " << filename << "\n";
    return;
  }

  out << "# Optimized Fuzzy System Parameters\n";
  out << "# Generated by GA-Fuzzy Optimizer\n";
  out << "# Date: " << __DATE__ << " " << __TIME__ << "\n\n";

  out << "# Performance Metrics\n";
  out << "# Training   - MSE: " << trainMetrics.mse << ", F1: " << trainMetrics.f1_score() << "\n";
  out << "# Validation - MSE: " << valMetrics.mse << ", F1: " << valMetrics.f1_score() << "\n\n";

  out << "# Chromosome (66 parameters for 6 fuzzy variables)\n";
  out << "# Format: SpeedChange(13), HeadingChange(13), VerticalRateChange(13),\n";
  out << "#         AltitudeChange(13), TimeGap(7), AnomalyLevel(7)\n\n";

  for (size_t i = 0; i < best.genes.size(); ++i) {
    out << best.genes[i];
    if (i < best.genes.size() - 1)
      out << ",";
    if ((i + 1) % 13 == 0 && i < 51)
      out << "\n";
    else if ((i + 1) == 59 || (i + 1) == 66)
      out << "\n";
  }

  out.close();
  std::cout << "\nOptimized parameters saved to: " << filename << "\n";
}

int main(int argc, char* argv[]) {
  std::cout << "========================================\n";
  std::cout << "ADS-B FUZZY SYSTEM GA OPTIMIZER\n";
  std::cout << "========================================\n\n";

  if (argc < 2) {
    printUsage(argv[0]);
    return 1;
  }

  // Parse arguments
  std::string csvPath = argv[1];
  int         generations = 100;
  int         populationSize = 100;
  double      trainSplit = 0.8;
  std::string outputFile = "results/optimized_params.txt";

  for (int i = 2; i < argc - 1; i += 2) {
    std::string arg = argv[i];
    if (arg == "--generations")
      generations = std::stoi(argv[i + 1]);
    else if (arg == "--population")
      populationSize = std::stoi(argv[i + 1]);
    else if (arg == "--train-split")
      trainSplit = std::stod(argv[i + 1]);
    else if (arg == "--output")
      outputFile = argv[i + 1];
  }

  std::cout << "Configuration:\n";
  std::cout << "  Input CSV:      " << csvPath << "\n";
  std::cout << "  Generations:    " << generations << "\n";
  std::cout << "  Population:     " << populationSize << "\n";
  std::cout << "  Train/Val:      " << (trainSplit * 100) << "% / " << ((1.0 - trainSplit) * 100)
            << "%\n";
  std::cout << "  Output file:    " << outputFile << "\n\n";

  try {
    std::cout << "Step 1: Data Preprocessing\n";
    std::cout << std::string(50, '-') << "\n";

    adsb::AdsbDataPreprocessor preprocessor;
    auto [inputs, outputs] = preprocessor.process(csvPath);

    if (inputs.empty()) {
      std::cerr << "Error: No valid samples after preprocessing\n";
      return 1;
    }

    std::cout << "\nStep 2: Train/Validation Split\n";
    std::cout << std::string(50, '-') << "\n";

    size_t trainSize = static_cast<size_t>(inputs.size() * trainSplit);

    std::vector<std::map<std::string, double>> trainInputs(inputs.begin(),
                                                           inputs.begin() + trainSize);
    std::vector<double> trainOutputs(outputs.begin(), outputs.begin() + trainSize);

    std::vector<std::map<std::string, double>> valInputs(inputs.begin() + trainSize, inputs.end());
    std::vector<double> valOutputs(outputs.begin() + trainSize, outputs.end());

    std::cout << "Training samples:   " << trainInputs.size() << "\n";
    std::cout << "Validation samples: " << valInputs.size() << "\n";

    std::cout << "\nStep 3: Baseline Evaluation\n";
    std::cout << std::string(50, '-') << "\n";

    ga::Chromosome defaultChromosome;

    auto baselineTrainMetrics =
        analysis::Validator::evaluate(trainInputs, trainOutputs, defaultChromosome);
    auto baselineValMetrics =
        analysis::Validator::evaluate(valInputs, valOutputs, defaultChromosome);

    analysis::Validator::printMetrics("Baseline Training", baselineTrainMetrics);
    analysis::Validator::printMetrics("Baseline Validation", baselineValMetrics);

    std::cout << "\nStep 4: GA Optimization\n";
    std::cout << std::string(50, '-') << "\n";

    ga::Fitness  fitness(trainInputs, trainOutputs);
    ga::GAEngine ga(populationSize, generations, 0.8, 0.2, 3);
    ga.setFitnessEvaluator(&fitness);

    std::cout << "Starting optimization...\n\n";
    ga.run();

    std::cout << "\nStep 5: Optimized System Evaluation\n";
    std::cout << std::string(50, '-') << "\n";

    const auto& bestChromosome = ga.bestChromosome();

    auto optTrainMetrics = analysis::Validator::evaluate(trainInputs, trainOutputs, bestChromosome);
    auto optValMetrics = analysis::Validator::evaluate(valInputs, valOutputs, bestChromosome);

    analysis::Validator::printMetrics("Optimized Training", optTrainMetrics);
    analysis::Validator::printMetrics("Optimized Validation", optValMetrics);

    std::cout << "\nStep 6: Final Summary\n";
    std::cout << std::string(50, '-') << "\n\n";

    double trainImprovement = ((optTrainMetrics.f1_score() - baselineTrainMetrics.f1_score()) /
                               baselineTrainMetrics.f1_score()) *
                              100.0;
    double valImprovement = ((optValMetrics.f1_score() - baselineValMetrics.f1_score()) /
                             baselineValMetrics.f1_score()) *
                            100.0;

    std::cout << "Performance Comparison:\n";
    std::cout << std::setw(20) << std::left << "" << std::setw(12) << "Baseline" << std::setw(12)
              << "Optimized" << std::setw(12) << "Improvement\n";
    std::cout << std::string(56, '-') << "\n";

    std::cout << std::setw(20) << std::left << "Train F1:" << std::setw(12) << std::fixed
              << std::setprecision(4) << baselineTrainMetrics.f1_score() << std::setw(12)
              << optTrainMetrics.f1_score() << std::setw(10) << std::setprecision(2)
              << trainImprovement << "%\n";

    std::cout << std::setw(20) << std::left << "Val F1:" << std::setw(12) << std::setprecision(4)
              << baselineValMetrics.f1_score() << std::setw(12) << optValMetrics.f1_score()
              << std::setw(10) << std::setprecision(2) << valImprovement << "%\n";

    std::cout << "\n"
              << std::setw(20) << std::left << "Train MSE:" << std::setw(12) << std::setprecision(4)
              << baselineTrainMetrics.mse << std::setw(12) << optTrainMetrics.mse << "\n";

    std::cout << std::setw(20) << std::left << "Val MSE:" << std::setw(12) << baselineValMetrics.mse
              << std::setw(12) << optValMetrics.mse << "\n\n";

    double trainValGap = optTrainMetrics.f1_score() - optValMetrics.f1_score();
    if (trainValGap > 0.15) {
      std::cout << " Warning: Possible overfitting detected\n";
      std::cout << " Train/Val F1 gap: " << trainValGap << "\n\n";
    }

    saveOptimizedParameters(outputFile, bestChromosome, optTrainMetrics, optValMetrics);

    std::cout << "\nGenerating analysis files...\n";
    analysis::Validator::saveDetailedResults(trainInputs, trainOutputs, valInputs, valOutputs,
                                             baselineTrainMetrics, baselineValMetrics,
                                             optTrainMetrics, optValMetrics, bestChromosome);

    std::cout << "\n" << std::string(50, '=') << "\n";
    std::cout << "OPTIMIZATION COMPLETE\n";
    std::cout << std::string(50, '=') << "\n";

    return 0;

  } catch (const std::exception& e) {
    std::cerr << "\nError: " << e.what() << "\n";
    return 1;
  }
}
